version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    network_mode: "host"
  
  consignment-service:
    build: ./consignment-service
    network_mode: "host"
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    network_mode: "host"
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"