version: '3.1'

services:
  user-cli:
    build: ./user-cli
    network_mode: "host"
    
  consignment-cli:
    build: ./consignment-cli
    network_mode: "host"
  
  consignment-service:
    build: ./consignment-service
    network_mode: "host"
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"

  vessel-service:
    build: ./vessel-service
    network_mode: "host"
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"

  user-service:
    build: ./user-service
    network_mode: "host"
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":5001"
      MICRO_BROKER: "nats"
      MICRO_BROKEN_ADDRESS: "127.0.0.1:4222"
      DB_NAME: "postgres"
      DB_HOST: "127.0.0.1"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  email-service:
    build: ./email-service
    network_mode: "host"
    ports:
      - 50054:50051
    environment:
      MICRO_ADDRESS: ":5001"
      MICRO_BROKER: "nats"
      MICRO_BROKEN_ADDRESS: "127.0.0.1:4222"

  datastore:
    image: mongo
    network_mode: "host"
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432
    network_mode: "host"